# Generated by Django 4.0.6 on 2022-08-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=15)),
                ('school_address', models.CharField(max_length=30)),
                ('school_email', models.EmailField(max_length=45)),
                ('location', models.CharField(max_length=24)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.CharField(max_length=1)),
                ('date_issued', models.DateField()),
                ('profile_picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers_Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('unit_speciality', models.CharField(choices=[('K', 'Kotlin'), ('P', 'Python'), ('R', 'Research'), ('P', 'Personal Development'), ('N', 'Navigating Your Journey'), ('P', 'Product Design'), ('I', 'Internet Of Things'), ('D', 'Django'), ('D', 'Design'), ('J', 'Java Script'), ('R', 'React')], max_length=15, null=True)),
                ('contact', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=45)),
                ('profile', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=45)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('P', 'Prefer not to say')], max_length=2, null=True)),
                ('adress', models.TextField(max_length=20)),
                ('stream', models.CharField(choices=[('A', 'Adalab'), ('H', 'Hopperlab'), ('A', 'Anitab')], max_length=2, null=True)),
                ('room', models.CharField(choices=[('C', 'Chalbi'), ('S', 'Serengeti'), ('T', 'Tanga'), ('M', 'Manda'), ('K', 'Kivu'), ('K', 'Kalahari'), ('A', 'Abaderes'), ('S', 'Stavo'), ('M', 'Mara'), ('S', 'Serengeti'), ('R', 'Rusinga')], max_length=7, null=True)),
                ('age', models.PositiveBigIntegerField(verbose_name=2)),
                ('admission_number', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('emergency_contact', models.IntegerField()),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='School_Student', to='system.school')),
            ],
        ),
    ]
