# Generated by Django 4.0.6 on 2022-08-11 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=15)),
                ('Last_name', models.CharField(max_length=15)),
                ('Occupation', models.CharField(choices=[('C', 'Chef'), ('G', 'Gardener'), ('M', 'Matron'), ('T', 'Trainors'), ('A', 'Accountant'), ('E', 'Event Co-ordinator'), ('E', 'Engineer'), ('G', 'Gatemen'), ('C', 'Cooks'), ('D', 'Dean')], max_length=8, null=True)),
                ('Email', models.EmailField(max_length=45)),
                ('Contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School_Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_fees', models.ImageField(upload_to='')),
                ('amount_paid', models.IntegerField()),
                ('balance', models.ImageField(upload_to='')),
                ('reciept', models.CharField(max_length=4)),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_School_Fees', to='system.student')),
            ],
        ),
        migrations.CreateModel(
            name='School_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=15)),
                ('account_number', models.IntegerField()),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='School_Account_School', to='system.school')),
            ],
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(verbose_name=100)),
                ('amount_balance', models.IntegerField()),
                ('receipt_number', models.IntegerField()),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_Reciept', to='system.student')),
                ('school_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='School_Reciept', to='system.school')),
            ],
        ),
        migrations.CreateModel(
            name='Library_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_issued', models.DateTimeField()),
                ('Return_date', models.DateTimeField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Library_Management_Student', to='system.student')),
            ],
        ),
        migrations.CreateModel(
            name='Academic_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=4, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Academic_Analysis_Student', to='system.student')),
            ],
        ),
    ]
