# Generated by Django 4.0.6 on 2022-08-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_staff_school_fees_school_account_reciept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_id',
            name='Student',
            field=models.CharField(max_length=45),
        ),
    ]
